# Generated by Django 4.2.3 on 2023-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0003_alter_student_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
