# Generated by Django 4.2.3 on 2023-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='materials_provided',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
