# Generated by Django 4.2.3 on 2023-10-08 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_App', '0005_student_materials_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 8, 14, 10, 4, 292984, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
